mod 'razorsedge/openvmtools', '1.0.0'
mod 'puppetlabs/apache', '1.7.1'
mod 'puppetlabs/concat', '2.0.0'
mod 'puppetlabs/stdlib', '4.9.0'
mod 'nanliu/staging', '1.0.3'
mod 'adrien/steam', '0.0.2'
mod 'xonotic',
  :git => 'https://github.com/tylermauthe/puppet-xonotic'